name: claude-ai
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python Base
  - python=3.10
  - pip
  
  # Scientific Computing
  - numpy=1.25.2
  - pandas=2.1.3
  - scikit-learn=1.3.2
  
  # Machine Learning & AI
  - pytorch=2.1.1
  - transformers=4.35.2
  
  # Web Framework
  - flask=2.3.3
  
  # Database
  - sqlalchemy=2.0.23
  - sqlite
  
  # Development Tools
  - pytest=7.4.3
  - black=23.11.0
  - flake8=6.1.0
  - jupyter
  - ipykernel
  
  # System dependencies
  - git
  
  # من طریق pip نصب می‌شوند (پکیج‌های خاص)
  - pip:
    # LLM & RAG
    - langchain==0.0.335
    - langchain-community==0.0.38
    - sentence-transformers==2.2.2
    - chromadb==0.4.15
    
    # Persian NLP
    - hazm==0.7.0
    - parsivar==0.2.3
    
    # Document Processing  
    - python-docx==0.8.11
    - PyPDF2==3.0.1
    - python-magic-bin==0.4.14; sys_platform == "win32"
    - python-magic==0.4.27; sys_platform != "win32"
    
    # Text Processing
    - nltk==3.8.1
    
    # Web Extensions
    - flask-cors==4.0.0
    - flask-wtf==1.2.1
    - jinja2==3.1.2
    - wtforms==3.1.0
    
    # Utilities
    - python-dotenv==1.0.0
    - requests==2.31.0
    - tqdm==4.66.1
    - pydantic==2.5.0
    
    # Testing
    - pytest-flask==1.3.0
    
    # Optional API packages
    # - openai==1.3.6
    # - anthropic==0.7.8
    # - ollama==0.1.7